### ISSUE TITLE
Cannot open General Settings page when using only spree_backend

### ISSUE THREAD

**Issue by kitwalker12** [spree/spree#8137] opened 2017-07-13 00:09 UTC
## Context
I'm using only spree_backend & spree_core while mounting it on a custom path. I've included AuthenticationHelpers & CurrentUserHelpers and everything works fine. The only problem I'm facing is that I cannot open General Settings page in the Admin view. I don't really need it but it's bugging me that this page is giving me an error.

## Expected Behavior
On clicking "General Settings" in the Spree Backend, `/backend/app/views/spree/admin/general_settings/edit.html.erb` should be rendered

## Actual Behavior
The logs show the following:
```
Started GET "/spree/admin/general_settings/edit" for ::1 at 2017-07-12 16:48:48 -0700
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", XX], ["LIMIT", 1]]
  Spree::Role Load (0.3ms)  SELECT "spree_roles".* FROM "spree_roles" INNER JOIN "spree_role_users" ON "spree_roles"."id" = "spree_role_users"."role_id" WHERE "spree_role_users"."user_id" = $1  [["user_id", XX]]
Processing by Spree::Admin::GeneralSettingsController#edit as HTML
Filter chain halted as :clear_cache rendered or redirected
Completed 204 No Content in 1ms (ActiveRecord: 0.0ms)
```

Struggling to understand why `clear_cache` action would be automatically called on visiting "General Settings" page.

## Your Environment
- ruby-2.3.1
- rails (5.0.2)
- puma (3.9.0)
- Route
```
    authenticate :user, lambda { |u| u.has_spree_role? :admin } do
      Spree::Core::Engine.add_routes do
        ...<custom routes>
      end
      mount Spree::Core::Engine, at: '/spree'
    end
```
- Gemfile
```
    spree_api (3.2.1)
      rabl (~> 0.13.1)
      spree_core (= 3.2.1)
      versioncake (~> 3.1.0)
    spree_backend (3.2.1)
      bootstrap-sass (~> 3.3)
      jquery-rails (~> 4.1)
      jquery-ui-rails (~> 5.0)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.2.1)
      spree_core (= 3.2.1)
    spree_core (3.2.1)
      activemerchant (~> 1.59)
      acts-as-taggable-on (~> 4.0)
      acts_as_list (~> 0.8)
      awesome_nested_set (~> 3.1.1)
      cancancan (~> 1.10.1)
      carmen (~> 1.0.0)
      deface (~> 1.0)
      ffaker (~> 2.2.0)
      font-awesome-rails (~> 4.0)
      friendly_id (~> 5.1.0)
      highline (~> 1.6.18)
      kaminari (~> 0.17)
      monetize (~> 1.1)
      paperclip (~> 4.3.0)
      paranoia (~> 2.2.0.pre)
      premailer-rails
      rails (~> 5.0.0)
      ransack (~> 1.8.0)
      responders
      sprockets-rails
      state_machines-activerecord (~> 0.2)
      stringex
      twitter_cldr (~> 3.0)
    spree_gateway (3.2.0.beta)
      spree_core (>= 3.1.0, < 4.0)
```

**Comment by kushniryb** [comment] 2018-05-21 13:15
Can't reproduce on my local machine. 
@bbonislawski Should we close this for now?

**Comment by bbonislawski** [comment] 2018-05-21 13:17
Yeah, if it's not reproduceable then we can't do anything. If OP can provide steps to reproduce then I'll reopen it.

**Closed by bbonislawski** 2018-05-21 13:17 UTC
Labels: Admin Panel, Bug, unverified
