### ISSUE TITLE
payments.valid

### ISSUE THREAD

**Issue by vazirj** [spree/spree#6397] opened 2015-05-18 10:53 UTC
Inside 
 spree/core/app/models/spree/payment.rb
line 59
```ruby
 scope :valid, -> { where.not(state: %w(failed invalid)) }
```
should **void** be included on this statement?
```ruby
 scope :valid, -> { where.not(state: %w(failed invalid void)) }
```

**Comment by JDutil** [comment] 2015-05-18 15:24
Duplicate of https://github.com/spree/spree/issues/5518

**Closed by JDutil** 2015-05-18 15:24 UTC
Labels: unverified
