### ISSUE TITLE
[2-4-stable] exception during order merge if product has missing availability

### ISSUE THREAD

**Issue by masterkain** [spree/spree#6274] opened 2015-04-10 13:55 UTC
On [this line](https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/order.rb#L484) we are currently parsing order line items and merge them into the caller order.

problem is that if the `AvailabilityValidator` (or better -- `quantifier can_supply?`) returns false here (perhaps availability changed before the merge occurs) this will raise, and since `merge!` is called in `set_current_order` in controller, the user will stare at an error.

unsure what the course of resolution would be. delete lines?

**Comment by JDutil** [comment] 2015-04-10 14:18
This is a duplicate of https://github.com/spree/spree/issues/5976 I believe we should remove the line item or reduce the quantity to what is available, and display a message to the customer explaining what happened.

**Closed by JDutil** 2015-04-10 14:18 UTC
Labels: unverified
