### ISSUE TITLE
Heroku deployment fails

### ISSUE THREAD

**Issue by eugenekorpan** [spree/spree#10655] opened 2021-01-08 10:16 UTC
Tried to deploy a demo app to heroku, faced an error. Please, see screenshot.
![heroku-deployment-fails](https://user-images.githubusercontent.com/363108/104003592-45f6ed00-51ab-11eb-8a0c-1f4ee50cb6bc.png)

**Comment by TheMissingNTLDR** [comment] 2021-01-09 17:16
Yes I can confirm that Heroku Deployments Fails using "Heroku Elements" Buttons.
https://elements.heroku.com/buttons/spree/spree

This is just straight out of box Button click and clicking Deployment button. No extra steps required.
Log file is as below.
My steps may not match the OP but I simply logged in to Heroku website and clicked on deploy "button".

`-----> Ruby app detected
-----> Compiling Ruby/Rails
WARNING:  You don't have /app/.gem/ruby/2.6.0/bin in your PATH,
	  gem executables will not run.
Successfully installed concurrent-ruby-1.1.7
HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.
If you are upgrading your Rails application from an older version of Rails:
Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.
If you are starting a NEW Rails application, you can ignore this notice.
For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
Successfully installed i18n-1.8.7
Successfully installed tzinfo-2.0.4
Successfully installed zeitwerk-2.4.2
Successfully installed activesupport-6.1.1
Successfully installed rack-2.2.3
Successfully installed rack-test-1.1.0
Building native extensions. This could take a while...
Successfully installed racc-1.5.2
Successfully installed nokogiri-1.11.1-x86_64-linux
Successfully installed crass-1.0.6
Successfully installed loofah-2.8.0
Successfully installed rails-html-sanitizer-1.3.0
Successfully installed rails-dom-testing-2.0.3
Successfully installed builder-3.2.4
Successfully installed erubi-1.10.0
Successfully installed actionview-6.1.1
Successfully installed actionpack-6.1.1
Successfully installed thor-1.0.1
Successfully installed method_source-1.0.0
Successfully installed railties-6.1.1
Parsing documentation for concurrent-ruby-1.1.7
Installing ri documentation for concurrent-ruby-1.1.7
Parsing documentation for i18n-1.8.7
Installing ri documentation for i18n-1.8.7
Parsing documentation for tzinfo-2.0.4
Installing ri documentation for tzinfo-2.0.4
Parsing documentation for zeitwerk-2.4.2
Installing ri documentation for zeitwerk-2.4.2
Parsing documentation for activesupport-6.1.1
Installing ri documentation for activesupport-6.1.1
Parsing documentation for rack-2.2.3
Installing ri documentation for rack-2.2.3
Parsing documentation for rack-test-1.1.0
Installing ri documentation for rack-test-1.1.0
Parsing documentation for racc-1.5.2
Installing ri documentation for racc-1.5.2
Parsing documentation for nokogiri-1.11.1-x86_64-linux
Installing ri documentation for nokogiri-1.11.1-x86_64-linux
Parsing documentation for crass-1.0.6
Installing ri documentation for crass-1.0.6
Parsing documentation for loofah-2.8.0
Installing ri documentation for loofah-2.8.0
Parsing documentation for rails-html-sanitizer-1.3.0
Installing ri documentation for rails-html-sanitizer-1.3.0
Parsing documentation for rails-dom-testing-2.0.3
Installing ri documentation for rails-dom-testing-2.0.3
Parsing documentation for builder-3.2.4
Installing ri documentation for builder-3.2.4
Parsing documentation for erubi-1.10.0
Installing ri documentation for erubi-1.10.0
Parsing documentation for actionview-6.1.1
Installing ri documentation for actionview-6.1.1
Parsing documentation for actionpack-6.1.1
Installing ri documentation for actionpack-6.1.1
Parsing documentation for thor-1.0.1
Installing ri documentation for thor-1.0.1
Parsing documentation for method_source-1.0.0
Installing ri documentation for method_source-1.0.0
Parsing documentation for railties-6.1.1
Installing ri documentation for railties-6.1.1
Done installing documentation for concurrent-ruby, i18n, tzinfo, zeitwerk, activesupport, rack, rack-test, racc, nokogiri, crass, loofah, rails-html-sanitizer, rails-dom-testing, builder, erubi, actionview, actionpack, thor, method_source, railties after 26 seconds
20 gems installed
WARNING:  You don't have /app/.gem/ruby/2.6.0/bin in your PATH,
	  gem executables will not run.
Successfully installed bundler-2.2.4
Parsing documentation for bundler-2.2.4
Installing ri documentation for bundler-2.2.4
Done installing documentation for bundler after 3 seconds
1 gem installed
      create  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  .gitattributes
      create  Gemfile
         run  git init from "."
Initialized empty Git repository in /tmp/build_557e97f2_/sandbox/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/spring
      create  bin/yarn
      remove  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/cable.yml
      create  config/puma.rb
      create  config/spring.rb
      create  config/storage.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_1.rb
      create  config/initializers/permissions_policy.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      create  test/system
      create  test/system/.keep
      create  test/application_system_test_case.rb
      create  storage
      create  storage/.keep
      create  tmp/storage
      create  tmp/storage/.keep
      remove  app/javascript
      remove  config/initializers/cors.rb
      remove  config/initializers/new_framework_defaults_6_1.rb
-----> Using Ruby version: ruby-2.6.6
-----> Installing dependencies using bundler 1.17.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4
       The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/............
       Fetching gem metadata from https://rubygems.org/.............
       Fetching gem metadata from https://rubygems.org/.............
       Resolving dependencies....
       Bundler could not find compatible versions for gem "rails":
         In Gemfile:
           rails (~> 6.1.1)
       
           spree was resolved to 4.1.13, which depends on
             spree_core (= 4.1.13) was resolved to 4.1.13, which depends on
               rails (~> 6.0.0)
       Bundler Output: The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
       Fetching gem metadata from https://rubygems.org/............
       Fetching gem metadata from https://rubygems.org/.............
       Fetching gem metadata from https://rubygems.org/.............
       Resolving dependencies....
       Bundler could not find compatible versions for gem "rails":
         In Gemfile:
           rails (~> 6.1.1)
       
           spree was resolved to 4.1.13, which depends on
             spree_core (= 4.1.13) was resolved to 4.1.13, which depends on
               rails (~> 6.0.0)
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
`

**Comment by TheMissingNTLDR** [comment] 2021-01-10 13:24
I am not sure if we need to reject this as it might be a duplicate of a similar or a same issue?
https://github.com/spree/spree/issues/10615

**Comment by kelteseth** [comment] 2021-01-11 07:04
@TheMissingNTLDR it is the same issue. I think we can close this one then.

**Comment by damianlegawiec** [comment] 2021-01-26 08:30
This is working again :)

**Closed by damianlegawiec** 2021-01-26 08:30 UTC
Labels: Needs Confirmation
