### ISSUE TITLE
500 Error on Cloned Products

### ISSUE THREAD

**Issue by cloudrck** [spree/spree#6606] opened 2015-07-18 01:11 UTC
This happens on copied products. It doesn't seem to be cloning correctly on Clones of Clones.

Ruby 2.1
PostgreSQL 9.3
Unicorn

1.) Create Product (A)
2.) Clone Product (A) to create product (B)
3.)Clone Product (B) to create Product (C)
3.) Edit, and click Update on product (C)
4.) 500 error, nothing gets updated.

or

3) Click on Variant or Properties on product (C)
4) 500 error

https://gist.github.com/cloudrck/130f4fc87410ccbeb6d5

**Comment by jasonfb** [comment] 2015-08-18 15:46
what is the "500 error" ? Generally when you see that that means there is a stacktrace associated with the error, please include stacktrace.

**Comment by cloudrck** [comment] 2015-08-18 23:05
It's with the link I provided.

**Comment by damianlegawiec** [comment] 2016-01-31 10:11
Cannot reproduce on 3.1.0.beta - closing

**Closed by damianlegawiec** 2016-01-31 10:11 UTC
Labels: unverified
