### ISSUE TITLE
spree 2-3 stable, free shipping not remove clearly, after add more product

### ISSUE THREAD

**Issue by dieuit07** [spree/spree#5248] opened 2014-08-21 10:44 UTC
Hi everyone, When to step checkout - payment info. I enter payment code FREESHIP, then it apply greate, and redirect to step review and confirm. 
Then I not submit yet and go back to add more product. I see the free shipping adjustment is removed.
But when I enter code FREESHIP in step payment again, It throw bug: "The coupon code has already been applied to this order". And the adjustment freeship not create.

Debug in database I see it still not remove from `spree_orders_promotions`.

COuld I code wrong somewhere or it 's an missing code of spree?

**Comment by JDutil** [comment] 2015-01-28 17:50
Duplicate of https://github.com/spree/spree/issues/5248

**Comment by JDutil** [comment] 2015-01-28 17:51
Duplicate of https://github.com/spree/spree/issues/5881 I mean.

**Closed by JDutil** 2015-01-28 17:50 UTC
Labels: unverified
