### ISSUE TITLE
accessing checkout steps prematurely may end up with exceptions

### ISSUE THREAD

**Issue by masterkain** [spree/spree#7176] opened 2016-03-05 15:10 UTC
I'm investigating exception reports on checkout views, especially /checkout/payment and /checkout/delivery.

if you have an order in cart state and its user visits for some reason /checkout/payment and /checkout/delivery you may end up with different situations, for the payment we get:

```
Showing /private/tmp/spree/frontend/app/views/spree/checkout/edit.html.erb where line #2 raised:

undefined method `+' for nil:NilClass
Extracted source (around line #2):

<% content_for :google_analytics do %>
  <%= render partial: 'spree/shared/google_checkout.js', locals: { order: @order, step_number: (@order.checkout_steps.index(@order.state) + 1) } %>
<% end %>
```

and this is kinda true whereas `checkout_steps` is involved.

for the address step we just render the view, but perhaps, and only perhaps, shouldn't the myriad of before actions in checkout controller also check if the order is in state cart before changing its state in `set_state_if_present` to allow for a redirect to the first step?

**Comment by hughdavenport** [comment] 2016-03-14 03:16
Steps to reproduce this on fresh clone:
```
git clone https://github.com/spree/spree
cd spree
bundle install
bundle exec rake sandbox
cd sandbox
rails server
```

Browse to http://localhost:3000, then
* Create an account
* Login
* Select a product
* Add to cart
* DO NOT CLICK CHECKOUT
* Browse manually to http://localhost:3000/checkout/payment

You should see the problem there. Due to having a state of "cart" which isn't included in the model's checkout_steps, so index returns nil.

Note, you need to be logged in, otherwise it will use the hook `check_registration` which is added by the `spree_auth_devise` gem and set the state to "registration".

**Comment by priyank-gupta** [comment] 2016-03-21 06:57
@masterkain I can verify this. Can you submit a PR for its fix ?

**Comment by lani13** [comment] 2018-05-24 10:28
Checked it. The bug doesn't occur anymore. @bbonislawski

**Comment by bbonislawski** [comment] 2018-05-24 10:28
Great. Closing

**Closed by bbonislawski** 2018-05-24 10:28 UTC
Labels: verified
