### ISSUE TITLE
spree not working with rails 5.1.1 

### ISSUE THREAD

**Issue by troias** [spree/spree#8061] opened 2017-06-12 23:38 UTC
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.1.1)

  In Gemfile:
    rails (~> 5.1.1) x86-mingw32

    spree (~> 3.2.0) x86-mingw32 was resolved to 3.2.0, which depends on
      spree_core (= 3.2.0) x86-mingw32 was resolved to 3.2.0, which depends on
        rails (~> 5.0.0) x86-mingw32

**Comment by joshRpowell** [comment] 2017-06-13 13:39
@troias see #8002

**Comment by damianlegawiec** [comment] 2017-06-19 08:02
Duplicate of https://github.com/spree/spree/issues/7986

**Closed by damianlegawiec** 2017-06-19 08:02 UTC

**Comment by troias** [comment] 2017-06-19 23:41
Still not working @damianlegawiec  can you explain better. I've even tried to create a new rails app and add spree 3.2.1 and it sitll does not work.

**Comment by troias** [comment] 2017-06-20 03:37
it does work when i use rails 4.26 but not rails 5.0 or 5.1

**Comment by damianlegawiec** [comment] 2017-06-25 19:12
Fixed via https://github.com/spree/spree/pull/8002
