### ISSUE TITLE
Error on Install Migration: 'relation "states" does not exist' when it tries to create spree_addresses

### ISSUE THREAD

**Issue by carltonsmith** [spree/spree#8223] opened 2017-08-09 19:55 UTC
## Context
When I run rails g spree:install --user_class=Spree::User it tells me I need to run rake db:migrate when it finishes. However, when I run migrate I get the following error:

-- create_table(:spree_addresses)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "states" does not exist

## Expected Behavior
The migrations should run without error

## Actual Behavior
The error above

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):
ruby version 2.2.7
rails version 4.2.7.1
gem 'spree', 	'~> 3.1.0'
gem 'spree_auth_devise', 	'~> 3.3'
gem 'spree_gateway',  ~> 3.3'
PostGres database running on Mac OS X Sierra 10.12.6

**Comment by bbonislawski** [comment] 2018-05-16 09:09
There was probably some other error that stopped migrations from working correctly. I cannot reproduce it and since there are not enough details, I'm closing this

**Closed by bbonislawski** 2018-05-16 09:09 UTC
