### ISSUE TITLE
Docker example not working

### ISSUE THREAD

**Issue by exocode** [spree/spree#8666] opened 2018-04-09 16:07 UTC
## Context
Cannot start docker example from readme

## Steps to Reproduce

docker run --rm -it -p 3000:3000 spreecommerce/spree:latest
open browser http://0.0.0.0:3000
Page should open spree demo

## Actual Behavior
ERR_CONNECTION_REFUSED

## Your Environment

Macbook Pro Docker version 18.03.0-ce, build 0520e24

**Comment by bbonislawski** [comment] 2018-04-10 07:53
Can you provide logs from your terminal? It works for me
<img width="665" alt="screen shot 2018-04-10 at 09 52 29" src="https://user-images.githubusercontent.com/7106611/38543489-f041f652-3ca4-11e8-8e29-ba76996b0b7b.png">

**Comment by ngphadke** [comment] 2018-04-20 04:31
Not working for me either. 

`➜ docker run --rm -it -p 3000:3000 spreecommerce/spree:latest
Unable to find image 'spreecommerce/spree:latest' locally
latest: Pulling from spreecommerce/spree
693502eb7dfb: Pulling fs layer
081cd4bfd521: Downloading  1.554MB/18.54MB
5d2dc01312f3: Downloading  1.293MB/42.5MB
54a5f7da9a4f: Waiting
168cf3f33330: Waiting
5edf1a65e7e1: Waiting
c95fc1e51b4d: Waiting
0164b0dd2de1: Waiting
1817efe794bf: Waiting
a56c643779c9: Waiting
b9e69a077ddc: Waiting
5c7d89cad86d: Waiting
9dcf96aa46a5: Waiting
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/9b/9b65c93a25b0d803f13ad6fb950dd2c307bdc005454bbccd1a854076170ee83b/data?Expires=1524241570&Signature=Mx8jqy3AtgT92tiCrkFfYqDKQKhwrvgy88SJiIbUHevnGcYW9jTLZHHT75SZ1vW4M~PRchDXLv6GWMwefPHtIdig3aOMOQQwLL6Z2l1QRev1md2PqdqyG3-OouT~yuAtFSteFSsDRnBEQKrD2oj-5vlYCvQAFBdVNwD5H1nKV4Q_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout.
See 'docker run --help'.`

**Comment by ozkar99** [comment] 2018-04-27 22:15
You should open browser to:
http://127.0.0.1:3000 or http://localhost:3000 

not
http://0.0.0.0:3000


check first answer on this:

https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0

**Comment by bbonislawski** [comment] 2018-05-21 10:34
I cannot reproduce it and author didn't answer. Closing for now

**Closed by bbonislawski** 2018-05-21 10:34 UTC
Labels: unverified
