### ISSUE TITLE
Duplicated payment with custom payment method

### ISSUE THREAD

**Issue by marcosteixeira** [spree/spree#6541] opened 2015-06-27 16:11 UTC
Hi,

My store uses a custom slip payment method (pt: boleto) and when we create a new slip payment the system also generates a invalid credit card payment.

I check and this payment is created at Spree::Order#assign_default_credit_card called when the order doesn't have a credit card payment.

https://github.com/spree/spree/blob/master/core/app/models/spree/order/checkout.rb#L92

Gemfile
```ruby
source 'https://rubygems.org'
ruby "2.2.1"


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.2'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'byebug', group: [:development, :test]
gem 'aws-sdk', '~> 1.6'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'sqlite3'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
end

group :production do
  gem 'rails_12factor'
  gem 'pg'
end

# Spree
gem 'spree', git: 'https://github.com/spree/spree.git', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: '3-0-stable'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n', branch: '3-0-stable'
gem 'spree_reviews', git: 'https://github.com/marcosteixeira/spree_reviews.git'
gem 'spree_static_content', github: 'spree/spree_static_content', branch: '3-0-stable'
gem 'spree_product_zoom',   github: 'spree/spree_product_zoom', branch: '3-0-stable'
gem 'stonez', git: 'https://github.com/techvitalcred/stonez.git'
gem 'httparty'
gem 'brcobranca'
```

**Comment by JDutil** [comment] 2015-06-29 14:37
Duplicate of https://github.com/spree/spree/issues/6499

**Closed by JDutil** 2015-06-29 14:37 UTC
Labels: unverified
