### ISSUE TITLE
Bug trying to create taxons within certain taxonomies

### ISSUE THREAD

**Issue by RyanQuey** [spree/spree#7777] opened 2017-01-09 21:18 UTC
Within the admin view, I created a taxonomy,  then right-click on the folder name to add a taxon.  I then type in the name for the taxon, and then click update. This returns me to the main taxonomy index view, and a green bar appears saying that I successfully updated the taxonomy.

However, although the taxonomy itself is created successfully, the taxon  disappears, cannot be selected or found elsewhere  (i.e., when trying to assign taxons to products), and is not visible when in the edit view for that taxonomy.

This occurred multiple times in trying out different taxonomy names and taxon names. However, what is even stranger is that before this occurred (and occurred multiple times), I just successfully created a different taxonomy and was able to create taxons within that taxonomy.

* Version used: 3.2.0.rc2

**Comment by Veske** [comment] 2017-07-03 20:42
Might be related?

```
Started PUT "/store/api/v1/taxonomies/5/taxons/" for 127.0.0.1 at 2017-07-03 23:40:45 +0300
Started GET "/store/api/v1/taxonomies/5/taxons" for 127.0.0.1 at 2017-07-03 23:40:45 +0300
Processing by Spree::Api::V1::TaxonsController#index as JSON
  Parameters: {"taxonomy_id"=>"5"}
  Spree::User Load (0.3ms)  SELECT  "spree_users".* FROM "spree_users" WHERE "spree_users"."deleted_at" IS NULL AND "spree_users"."spree_api_key" = $1 LIMIT $2  [["spree_api_key", ""], ["LIMIT", 1]]
  Spree::Preference Load (0.1ms)  SELECT  "spree_preferences".* FROM "spree_preferences" WHERE "spree_preferences"."key" = $1 LIMIT $2  [["key", "spree/api_configuration/requires_authentication"], ["LIMIT", 1]]
  Rendering /home/kaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spree_api-3.2.1/app/views/spree/api/errors/must_specify_api_key.v1.rabl
  Rendered /home/kaspar/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spree_api-3.2.1/app/views/spree/api/errors/must_specify_api_key.v1.rabl (0.9ms)
Filter chain halted as :authenticate_user rendered or redirected
Completed 401 Unauthorized in 79ms (Views: 77.3ms | ActiveRecord: 0.4ms)

```

On Spree 3.2.1. This error appears even tough I am logged in.

**Comment by bbonislawski** [comment] 2017-10-02 20:47
I guess that's the same issue as in #7503. It's fixed with js-tree update. Closing for now, please write here if the problem is still present on master branch

**Closed by bbonislawski** 2017-10-02 20:47 UTC
Labels: Admin Panel, Bug
