### ISSUE TITLE
Routing error: No route matches [GET] "/admin/orders/R689775778/customer_returns/3"

### ISSUE THREAD

**Issue by tommiller1** [spree/spree#7361] opened 2016-05-18 16:11 UTC
Hi,

Steps to reproduce:
1. Ship order
2. Create return authorization
3. Create new customer return
4. Click on "create reimbursement", it should take you to orders/R689775778/reimbursements/4/edit
5. Now click cancel, it will redirect you to orders/R689775778/customer_returns/3 which causes the routing error.

Another bug(?) on this page: orders/R689775778/return_authorizations/new
The amount under the 'charged' column is same as the pre-tax refund amount, surely it should display the amount charged to the customer (including taxes) ?

Regards.

**Comment by bbonislawski** [comment] 2017-10-02 21:23
Hello, I cannot reproduce it on current master. I'm closing it since it's probably outdated. Anyway, thanks for reporting. I really appreciate your help!

**Closed by bbonislawski** 2017-10-02 21:23 UTC
