### ISSUE TITLE
2.4.0rc2 Admin validations problem

### ISSUE THREAD

**Issue by williamweckl** [spree/spree#5551] opened 2014-10-31 14:13 UTC
I'm using 2.4.0rc2 and when I save a product with errors, the product isn't saved but no errors are displayed. The screen is reloaded and the success flash message appears.

**Comment by JDutil** [comment] 2015-02-16 20:34
I believe this is caused by:
https://github.com/globalize/globalize/issues/401

**Comment by JDutil** [comment] 2015-02-27 19:41
Closing as this is actually spree_i18n related, and I believe root cause is globalize.

**Closed by JDutil** 2015-02-27 19:41 UTC
Labels: verified
