### ISSUE TITLE
"We are unable to calculate shipping rates for the selected items."

### ISSUE THREAD

**Issue by freshnewegg** [spree/spree#7823] opened 2017-02-24 06:39 UTC
## Context

I was trying to set up the checkout process and there were so many errors that were undocumented! Having suffered solving this problem, I'd like to recommend the documentation being updated. In order to process checkout, there are many steps that need to be done.

you need to set up: zones, tax rates, tax categories, inventory locations, countries, states, payment methods etc etc. 

http://guides.spreecommerce.org/developer/checkout.html is not enough!

## Expected Behavior

There should be an error that tell you what is missing

## Actual Behavior

On the API side, it just says "We are unable to calculate shipping rates for the selected items."
On the website, during the address phase of checkout, a red box appears with no error message if the setup is not complete!

## Possible Fix

Update the documentation or put out a new guide to integrate checkout.

**Comment by alaadahmed** [comment] 2017-03-05 03:10
I have the same issue as @freshnewegg

**Comment by ouykjh** [comment] 2017-03-10 11:13
I think all things are in user doc: http://guides.spreecommerce.org/user/shipping_methods.html .

**Comment by azranel** [comment] 2017-03-10 11:56
Actually user (user on frontend) doesn't exactly need to know what's wrong IMO. It would be better to just log some info with `Rails.logger.info`, at least on development/test envs.

**Comment by quesurifn** [comment] 2017-05-30 19:06
They are not in the documentation. The parts of the documentation are outdated

**Comment by Qwertie-** [comment] 2017-07-24 04:15
Should be some logging for sure. Real pain trying to work out which setting is causing the issue.

**Comment by dylanfisher** [comment] 2017-07-25 15:37
I had some trouble debugging this issue recently and it turned out it was because the Spree seeds.rb code had been run multiple times, and I ended up with duplicate countries and states. In my case I was working with a new database so I could just delete_all the seeded data and re-seed the database.

**Comment by freshnewegg** [comment] 2017-07-25 15:53
basically it comes down to you have to follow the doc EXACTLY with a perfect setup. no mistakes. no forgiveness

its easier than debugging logging is a nightmare

**Comment by damianlegawiec** [comment] 2017-07-25 16:20
@dylanfisher this is fixed in 3.3, you won't have any duplicates in the database https://github.com/spree/spree/blob/master/guides/content/release_notes/3_3_0.md#added-missing-indexes-and-unique-indexes

**Comment by Qwertie-** [comment] 2017-07-25 16:37
@freshnewegg This pretty much. Often I have found its much easier to just drop the database when possible rather than try and work out what went wrong from the generic error messages. Often the best way to debug them is finding out where the error was made and disabling the exception to get a better error from rails.

**Closed** 2017-10-02 15:04 UTC
Labels: Documentation

**Comment by einSelbst** [comment] 2018-01-18 18:18
Having spent a couple of hours with this issue myself now I would like to add what was the solution in my case.
I did update spree from 3.09 -> 3.4.4, rails from 4.2.2 -> 5.1, ruby 2.2.3 -> 2.4.2
Because reasons I had to dump the database -> restore locally -> migrate -> dump again and restore into upgraded production system.

Among other things I run into the error mentioned here in this issue. The solution was:
Go into Admin -> Configurations -> Shipping methods
then inside every shipping method (edit) click the 'Update' button. 

After this the calculation started to work.

FWIW the exception is thrown in the method `ensure_available_shipping_rates` inside
`~/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spree_core-3.4.4/app/models/spree/order.rb` and can be debugged with `binding.pry` and `rails s`.

**Comment by arpancj** [comment] 2018-05-05 13:07
@einSelbst just had the same issue after upgrading from Spree 3.2 to 3.4. Editing each shipping method and clicking "update" fixed the issue.

**Comment by bigzoo** [comment] 2018-12-05 14:08
Just incase anyone else stumbles on this on Spree 3, I had set the currently on my calculator to USD. Changing it to the site's default currency (in my case EUR) fixed it

**Comment by mices** [comment] 2019-01-07 11:35
I'm having this problem in 3.6.4  I created a flat rate $0.0 shipping method for a country based zone I named United States which has only one country in it's countries list, United States When a customer tries to check out they get the error message "We are unable to calculate shipping rates for the selected items." I've confirmed my settings in rails console for Spree::Config.currency
> "USD"
and Spree::Config.default_country_id
> 232
So then what could the problem be?

**Comment by mices** [comment] 2019-01-08 02:07
I notice the spree_preferences table has a column named "key" Could this be the problem? maybe "key" is a  reserved name in some databases

**Comment by nut707** [comment] 2019-04-25 04:21
I've stucked with this error after upgrading spree from 3.1 to 3.6.
Editing each shipping method and clicking "update" - not worked for me.
The reason was that i've copied spree admin views to my project for some customising without deface. After i delete shipping_method views from **my** project folder and "reupdate" shipping methods in ui all works fine.

**Comment by AmitPatel-BoTreeConsulting** [comment] 2019-05-22 07:58
I am facing same issue. I migrated from 2.3 to 3.7. Even I get the issue with [sample spree application](https://spree3dot7.herokuapp.com) as well

![Screenshot_2019-05-22 Spree Demo Site](https://user-images.githubusercontent.com/1289894/58157168-6223de80-7c95-11e9-906a-269a732f35c0.png)

**Comment by jash** [comment] 2019-05-29 23:29
Had the same issue upgrading from Spree 3.1.13 to 3.7.  It works when I edit each shipping method and set the Display to "Both" (was blank).
![image](https://user-images.githubusercontent.com/2354/58597837-9d428680-822e-11e9-9c93-44eff419f362.png)

**Comment by vivek2007** [comment] 2020-01-08 03:27
> @dylanfisher this is fixed in 3.3, you won't have any duplicates in the database https://github.com/spree/spree/blob/master/guides/content/release_notes/3_3_0.md#added-missing-indexes-and-unique-indexes

An error did not allow to save this record:
We are unable to ship the selected item to your address. Please choose another shipping address.
![image](https://user-images.githubusercontent.com/5186673/71948085-e90dd300-31f4-11ea-9626-7934b7157f6e.png)

**Comment by ramesh2007** [comment] 2020-01-08 03:36
An error did not allow to save this record:
We are unable to ship the selected item to your address. Please choose another shipping address.
![image](https://user-images.githubusercontent.com/303450/71948454-0c854d80-31f6-11ea-9ec3-fc11e0bd2c51.png)

**Comment by shubham-kaushal** [comment] 2020-06-15 05:18
@damianlegawiec I met with this error “We are unable to calculate shipping rates for the selected items.” error in spree 4.1.7 Checked everything but nothing solved. Kindly suggest the solution to solve this?

**Comment by autotelik** [comment] 2021-01-19 17:47
Spree 4.1 and yep its still going ... literally nothing useful in the logs, just this error

**Comment by lshepstone** [comment] 2021-03-24 16:57
Experiencing the same issue with `4.2` – sample data works okay, but following the guides to set up a new delivery method etc. with a new database freshly seeded still shows this error. Will try debug further and post any findings here.

**Comment by zolzaya** [comment] 2021-04-28 08:41
hey @lshepstone, I facing same errors with new database. Do you found any solutions?

**Comment by funder7** [comment] 2021-08-15 17:36
Hello guys, I think that I've found the issue with my setup, maybe it can help somebody else: 
if you have the ext spree_multivendor installed, then a new column is added to the `spree_shipping_methods` table.
This column is the `vendor_id`, which cannot be set from the UI (the input element is missing). With a vendor_id, I was able to move to the next step.

**Comment by w3villa-renu-vishwakarma** [comment] 2024-04-02 05:51
I solve this issue by changing the shipping method display from none to both/frontend/backend from spree admin under configuration tab

**Comment by pemanorbu2** [comment] 2024-09-30 17:25
i got same error "We are unable to calculate shipping rates for the selected items."? 

Any Solution?
