### ISSUE TITLE
Spree Gateway generate invalid $0.0 payment record on checkout

### ISSUE THREAD

**Issue by oscarsiniscalchi** [spree/spree#6594] opened 2015-07-14 14:44 UTC
Hi, I am currently having an issue on my project using spree. I am not sure If I should post this issue here or if it belongs to spree_gateway but hopefully you guys can provide me with some insight.

Gemfile:
```
gem 'spree', '~> 3.0.1'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree_editor', github: 'spree-contrib/spree_editor', branch: '3-0-stable'
```

I have configured to use `Spree::Gateway::StripeGateway` as my Payment method and everything is working just fine except for one little detail:
When I place an order and check the payments for that order I can always see 2 payments, 
 - an invalid one with no transaction id and an amount of $0.0, 
 - and a valid one for the total of the order. 

I try debugging this thing myself but I could not understand where this is coming from, I could not find related issues or problems online, so I was wondering if there may be anything on my end that is causing this issue. Or if something any of you have experience before. In any case I did a horrible hack to get rid of it basically added a before action to the update of the OrderController that removes the $ 0.0 payment, but I would love to get rid of it in a different way ideally preventing it from being generated.

I would much appreciate any help/guidance as well as to know if anyone has ever experienced something similar.

<img width="890" alt="screen shot 2015-07-14 at 11 41 49 am" src="https://cloud.githubusercontent.com/assets/907991/8676076/ad8107aa-2a1d-11e5-9ff6-106e3a611bcb.png">

**Comment by JDutil** [comment] 2015-07-14 15:15
Duplicate of https://github.com/spree/spree/issues/6499

**Closed by JDutil** 2015-07-14 15:15 UTC
Labels: unverified

**Comment by oscarsiniscalchi** [comment] 2015-07-14 15:33
Thank you very much JDutil! will check the other issue.
