### ISSUE TITLE
Backend: order goes directly to complete when adding product in the cart after customer details were entered

### ISSUE THREAD

**Issue by frahugo** [spree/spree#6112] opened 2015-03-04 20:39 UTC
This happens when customer is an existing customer, with a payment profile in the database.

How to reproduce in the sandbox:
- Log in the backend
- Create a new order
- Add a product to the order
- Click on "Customer details" and select the customer (spree@example.com)
- Click on "Update"
- Click on "Cart"
- Add a second product.  Right after clicking the "+" sign, the order will finalize itself

When adding the product through the "Shipments" tab, everything works fine.

**Comment by hnatt** [comment] 2015-03-15 22:11
I can confirm.

This is because `advanceOrder` function is called on line item [add](https://github.com/spree/spree/blob/2-4-stable/backend/app/assets/javascripts/spree/backend/line_items_on_order_edit.js.erb#L52), [edit](https://github.com/spree/spree/blob/2-4-stable/backend/app/assets/javascripts/spree/backend/line_items.js.coffee#L51) and [delete](https://github.com/spree/spree/blob/2-4-stable/backend/app/assets/javascripts/spree/backend/line_items.js.coffee#L64). I have no idea what intention was behind this. *"If manager adds, edits or removes line item, advance the order to next status"*? Doesn't make any sense to me.

I caught this bug in 2.3, but then it got fixed by another bug -- `advanceOrder` is still being invoked, but it doesn't pass the API token in 2.3 like it does in 2.4, so the server responds with 401 Unauthorized and the order isn't getting advanced.

I suggest removing `advanceOrder` invocation from the three mentioned actions, but I may be missing something in my picture.

**Comment by JDutil** [comment] 2015-03-16 15:54
I think the issue with removing advanceOrder is that we never know how people have customized their checkout flow to work.  So we can't just assume that everyone needs to advance the same steps.  We ran into this similar issue before, and were able to resolve it by stopping the advancement before it would transition to complete.

**Comment by hnatt** [comment] 2015-03-16 17:03
But why an order has to be advanced to next stage when a manager just changes items in it?

**Comment by JDutil** [comment] 2015-03-16 18:25
To ensure shipments, taxes etc. are all properly recalculated again.

**Comment by frahugo** [comment] 2015-03-16 18:30
Suggestion: when shipments exist on the order, hide the Cart panel in the navigation.. This would solve this issue.

**Comment by JDutil** [comment] 2015-03-16 18:45
I believe we do once they are "shipped" until then I believe the intent is to allow CSR (Customer Service Reps) to make changes.  Will have to double check that though

**Comment by hnatt** [comment] 2015-03-16 18:47
Still sounds to me like the order shouldn't go to **next** state after the current, when admin changes items. From first up to current -- to ensure shipments, taxes etc. -- but why is it switching to the next one?

Easiest way to reproduce the behavior that buffles me in a sandbox for 2-4-stable:

1. As a guest user, add item to cart.
2. Log in to backend.
3. Find last uncompleted order, click "edit". Note that order's status is "cart".
4. Click "cart", edit item's quantity.
5. Note that order's status is changed to "address".

If "address" step wouldn't require user input to proceed, then after changing the item again, the order would proceed to next state and so on until reached final state or required some condition for accomplishing the step.

The problem in my particular app is that I added several checkout steps that don't require user input or any conditions, just for internal use. And now the order cycles through these states when admin changes line items. Am I misusing the checkout flow?

**Comment by frahugo** [comment] 2015-03-16 18:51
I agree with @hnatt ... On a new order, there is no need to update taxes, shipments while the state is "cart" (there is no address set anyway at that time, so it's impossible to compute taxes, shipments, shipping rates, ...).  When adding items to the cart through the admin, the state should stay "cart", until we add an address or create shipments.

**Comment by darbs** [comment] 2015-07-13 16:59
Also present in 3-0-stable. IMO we should not be advancing anywhere automagically in the backend. I would favor a dedicated 'Advance' button its safer and allows admin/authorized user to check everything.

**Comment by bbonislawski** [comment] 2018-05-21 08:59
I think this is safest option for users. If you need different way to handle it, customize it

**Closed by bbonislawski** 2018-05-21 08:59 UTC
Labels: verified
