### ISSUE TITLE
Back Order bug in 3.0.4

### ISSUE THREAD

**Issue by dimebar** [spree/spree#7328] opened 2016-04-29 15:31 UTC
Slight problem with backorders in 3.0.4, say I create 3 separate orders.

Order1 = 1 backorderable item
Order2 = 2 backorderable items
Order3 = 1 backorderable item

Giving me a total of -4 in stock.

If I manually update Oder2 to 1 backorderable item click update and set it back to 2 backorderable items.

Order1 is no longer backorderbale and is marked as on hand and ready to ship even though I still have -4 stock?

Any solution to this problem would be appreciated.

**Comment by glapworth** [comment] 2016-04-29 16:52
I can reproduce this issue:

Product x is backorderable and has 0 stock.

Order 1 contains shipment of 1 * Product X (on backorder)
Order 2 contains shipment of 2 * Product X (on backorder)
Order 3 contains shipment of 1 * Product X (on backorder)

Edit order 2, and change shipment to contain 1x Product X puts one item back in stock. This item gets allocated to Order 1 and order 1, product X is now marked as "On Hand".

**Comment by dajvido** [comment] 2017-05-12 07:10
I'll check if it still exists on the master. If so, I'll fix it.

**Comment by dajvido** [comment] 2017-05-12 08:17
On master bug still, exists, I'll handle it cc @damianlegawiec

**Comment by dajvido** [comment] 2017-06-05 05:42
It seems to be a bigger issue:
Every time you decrease your backorderable order it's letting know your count on hand to increase for reduced value. However, there isn't any flag which would notify count of hand that this was from backorderable instead of physical product so it triggers dividing "newly available" products over current backorderable orders. 
It would require modifying a method to know if it was a backorderable product or not and then trigger dividing functionality or not.
I am afraid I won't be able to do it this month due to my duties. If no one takes care about fixing it, I should be able in July to back to this. cc @damianlegawiec

**Comment by thanhtungka91** [comment] 2017-10-11 16:43
any update?

**Comment by bbonislawski** [comment] 2018-03-12 11:10
Fixed with #8629 .
Thanks for reporting!

**Closed by bbonislawski** 2018-03-12 11:10 UTC
Labels: Bug
