### ISSUE TITLE
failed 3-0-stable rspec backend

### ISSUE THREAD

**Issue by arthurtalkgoal** [spree/spree#6074] opened 2015-02-22 14:26 UTC
I wanna give a pull request on updating the friendly_id
https://github.com/spree/spree/pull/6070

but found the rspec failed, I tried to roll back my changes locally and still failed. Anyone has 3-0-stable and succeeded in the ***/spec/features/admin/orders/listing_spec.rb (line 130 and 145 for the order promotion search)***?

```
) Orders Listing searching orders should be able to search orders using only completed at input
     Failure/Error: within("table#listing_orders") { expect(page).not_to have_content("R200") }
       expected not to find text "R200" in "COMPLETED AT NUMBER RISKY STATE PAYMENT STATE SHIPMENT STATE CUSTOMER E-MAIL TOTAL 2015-02-23 R100 Risky cart balance due pending casimir@hilllbergstrom.biz $110.00 2015-02-21 R200 Safe cart annabel_hegmann@oberbrunner.info $0.00"
     # ./spec/features/admin/orders/listing_spec.rb:130:in `block (4 levels) in <top (required)>'
     # /home/.rvm/gems/ruby-2.0.0-p353@rails4/gems/capybara-2.4.4/lib/capybara/session.rb:285:in `within'
     # /home/.rvm/gems/ruby-2.0.0-p353@rails4/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
     # ./spec/features/admin/orders/listing_spec.rb:130:in `block (3 levels) in <top (required)>'

```

My codes have nothing to do with orders or promotion.

**Comment by JDutil** [comment] 2015-02-22 22:15
This is known failure don't worry about it.  Duplicate of #5877

**Closed by JDutil** 2015-02-22 22:15 UTC
Labels: unverified

**Comment by arthurtalkgoal** [comment] 2015-02-23 04:15
Oh, Thanks @JDutil,

Then can spree merge my pull request? as I have another pull request for the db/seeds for sqlite, current seeds has syntax error in sqlite.
