### ISSUE TITLE
Validation failure for out of stock line item when merging carts: "Quantity select is not available"

### ISSUE THREAD

**Issue by onedanshow** [spree/spree#6257] opened 2015-04-03 22:07 UTC
Steps to reproduce problem:

1) Log in, add an item to your logged-in cart.

2) Go into admin and take stock level for that item down to zero (backordering is off)

3) Log out (or open incognito window) and add something else to your guest cart.

4) Log back in in same window. When Spree tried to merge the logged-in cart and guest cart, this line of Spree::Order#merge! will throw the following error: https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/order.rb#L487

![screen shot 2015-04-03 at 5 02 25 pm](https://cloud.githubusercontent.com/assets/149438/6989601/3cf5a3b4-da23-11e4-92e6-868f77fde837.png)

Solutions:

Remove out of stock line items when merging cart? Check if backorderable first? Remove bang (!) on saved?

**Comment by JDutil** [comment] 2015-04-06 13:17
This is a duplicate of https://github.com/spree/spree/issues/5976 I think the best solution would probably be to remove out of stock items, and display a message to the customer indicating what has happened.

**Closed by JDutil** 2015-04-06 13:17 UTC
Labels: unverified

**Comment by onedanshow** [comment] 2015-04-06 14:00
Thanks for recognizing the duplicate.
