### ISSUE TITLE
DefaultPrice#default_price presenting deleted Price

### ISSUE THREAD

**Issue by joshRpowell** [spree/spree#8366] opened 2017-09-29 15:57 UTC
## Context
- We recently changed Price on one of our Products for the first time.  We noticed that Variants of the same Product with the same NEW Price showed up on an Order with one LineItem at the NEW Price and the other LineItem at the OLD Price.
![line_items_price](https://user-images.githubusercontent.com/6732638/31024089-f86f049a-a50b-11e7-9ef2-828a4e6561e7.png)

- Investigating the Order's Variants we found that the Variants had different default_prices
![variant_default_price](https://user-images.githubusercontent.com/6732638/31024090-f87ec9de-a50b-11e7-8299-97ba7bc3c686.png)

- Investigating further resulted in a default_price that was deleted when the price change was made. 
![verify_default](https://user-images.githubusercontent.com/6732638/31023659-8fd71478-a50a-11e7-8a62-0228cf90e700.png)

- DefaultPrice is defined here.
https://github.com/spree/spree/blob/034cd07d7775c014e3239b566b355b3aa16d7e71/core/app/models/concerns/spree/default_price.rb#L17

## Expected Behavior
A scoped result if a default price is deleted.

## Actual Behavior
Returns unscoped result refrencing a deleted default price. 

## Possible Fix
Change default price to a scoped result.
But would like to open to debate.  Not sure of the rational here.

## Steps to Reproduce

1. Create Spree::Variant
2. Change the Price
3. Delete old Price
4. Check Variant#default_price?  and Variant#has_default_price?

## Your Environment

* Version used: Ruby 2.4.1, Rails 5.1.4, Spree 3.3.1

**Comment by joshRpowell** [comment] 2017-09-29 16:37
For reference, the [Paranoia Gem](https://github.com/rubysherpas/paranoia#usage)

**Comment by tanmay3011** [comment] 2017-10-31 13:53
Hey @joshRpowell, Something seems to be missing in Steps to reproduce. Did you delete the variant and created a new one?

After changing the price of the new Variant
1. Existing price gets updated
2. No new price is created

So should I delete the existing price?

**Comment by GrzegorzStochel** [comment] 2018-05-18 09:40
I can't reproduce that, maybe something is missing in description ?

**Comment by bbonislawski** [comment] 2018-05-18 09:41
I couldn't reproduce it either. I'm closing it and will reopen if we get reproducible case

**Closed by bbonislawski** 2018-05-18 09:41 UTC
Labels: Bug, unverified
