### ISSUE TITLE
+/- quantity field in item show page and checkout page changes drastically by mouse hover

### ISSUE THREAD

**Issue by mimilettd** [spree/spree#8543] opened 2018-01-09 21:42 UTC
## Context

When you visit a product show page, for example, `http://localhost:3000/products/ruby-on-rails-tote` and try to adjust the quantity by clicking the increase or decrease selector, the quantity will increase drastically if you leave your mouse hovered over the selector. For example:

### Actual Behavior
<img src="http://g.recordit.co/7uax5KexCc.gif" alt="issue">

When you visit the checkout page and try to adjust the quantity by clicking the increase or decrease selector, the quantity will increase drastically if you leave your mouse hovered over the selector. Fore example:

### Actual Behavior
<img src="http://g.recordit.co/ty3ZyAV7NS.gif" alt="issue">

### Expected Behavior

When you interact with the quantity field and want to increase or decrease the value, it should change by 1 per click.

## Steps to Reproduce

1. Start up the development server and head to `/`
2. Click on any item
3. Click on the increase or decrease selector in the quantity field and let it hover without clicking again.

## Your Environment

* Version used: Ruby 2.4.2, Rails 5.1

**Comment by bbonislawski** [comment] 2018-01-10 10:51
I've tested it on Safari, Chrome and Firefox. Couldn't reproduce your problem. 

The only reason I can think of is that it's your browser freezing and when you click it's like you're holding button for some time.

Can someone reproduce it too?

**Comment by bbonislawski** [comment] 2018-03-08 14:01
No news since 2 months. Closing for now. I'll reopen it when proper reproduction steps will be provided

**Closed by bbonislawski** 2018-03-08 14:01 UTC
