### ISSUE TITLE
Products api is not working on brand new spree store

### ISSUE THREAD

**Issue by DamianPereira** [spree/spree#8292] opened 2017-09-07 01:34 UTC
## Context

I'm trying to setup an spree store following the steps on the [Getting started](http://guides.spreecommerce.org/developer/getting_started_tutorial.html) guide. After doing all steps I can start a rails server and see the store working. I can browse products without problem , and I can also login as admin and get the api key.

Everything seems to work, but when I try to use the api for products I get an erorr. I'm sending a GET request to localhost:3000/api/v1/products?token=[my key], I get a status 500 and the following error:

```
Showing /var/lib/gems/2.3.0/gems/spree_api-3.3.0/app/views/spree/api/v1/products/index.v1.rabl where line #3 raised:

SQLite3::SQLException: near "AS": syntax error: SELECT COUNT(DISTINCT count_column) FROM (SELECT  DISTINCT spree_products.id AS count_column, spree_products.* AS count_column FROM "spree_products" WHERE ("spree_products".deleted_at IS NULL or "spree_products".deleted_at >= '2017-09-07 01:04:38.680490') AND ("spree_products".discontinue_on IS NULL or "spree_products".discontinue_on >= '2017-09-07 01:04:38.680766') LIMIT ? OFFSET ?) subquery_for_count

```

## Expected Behavior

I should be able to see a list of the products. I can already see them in the store front-end, and I can see them in the db If I manually go check it with the sqlite terminal and manual queries (select * from spree_products). 

## Actual Behavior

It fails with the error above. The same query also fails with the same error while using the latest sqlite3 cli manually.

## Possible Fix

The request works fine (status 200) if I comment line 2 of /var/lib/gems/2.3.0/gems/spree_api-3.3.0/app/views/spree/api/v1/products/index.v1.rabl

node(:count) { @products.count }

The response lists products as expected. The only difference from the one on the documentation is that count is not in the output. The syntax for that request does not look valid, but maybe I messed up something? I tried the guide multiple times, reinstalling ruby and all gems.

## Steps to Reproduce

1. Follow every step in the getting started guide.
2. Do a GET request on localhost:3000/api/v1/products.json (I tried both curl and chrome, both ended on the same error).

## Your Environment

* Version used: Spree 3.3.0
* Gemfile and Gemfile.lock as text in a Gist: [Gist for all files](https://gist.github.com/DamianPereira/e58c71930444fbf55c02eb90371eab26)
* Any relevant stack traces ("Full trace" preferred): Included in Gist above.
* OS: ElementaryOS, which is based on ubuntu 16.04LTS
* Ruby version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

I suspect it's some ubuntu 16.04 library that is too out of date. But I have no idea which it might be. Would updating to ruby 2.4 be a good idea?

**Comment by DamianPereira** [comment] 2017-09-07 01:59
Updating to ruby 2.4.1 did not fix the issue. Error is exactly the same, except now everything is under  /var/lib/gems/2.4.0/gems/

**Comment by damianlegawiec** [comment] 2017-09-07 11:00
This will be fixed with Rails 5.1.4 release ( https://github.com/rails/rails/blob/v5.1.4.rc1/activerecord/CHANGELOG.md second item in the changelog)

**Comment by DamianPereira** [comment] 2017-09-07 12:27
Thanks! I wanted to use postgres for deployment, but since sqlite was the default DB I thought it was fine for dev. Should the getting started be updated with a "You might want to change DB engine to postgres, here's how"?

**Comment by DamianPereira** [comment] 2017-09-10 15:40
I updated to rails 5.1.4, and recreated everything, but the bug still persists. Is there anything else I should do?

**Closed** 2017-09-11 08:06 UTC
Labels: API, Bug

**Comment by htorohn** [comment] 2017-10-01 22:07
Hi DamianPereira,

Did you find a fix for this issue? I'm having the same problem with the same configuration as you.

**Comment by damianlegawiec** [comment] 2017-10-02 06:44
@htorohn please upgrade Spree to 3.3.2 - this will resolve the issue

**Comment by blset** [comment] 2019-01-16 15:47
I get the same behaviour on spree 3.7.rc1 and rails 5.2 on a brand new store

impossible to post a new product through the api

**Comment by blset** [comment] 2019-01-16 15:49
once I create manually one product, everything works as advertised through the api

**Comment by damianlegawiec** [comment] 2019-01-16 15:51
@blset can you provide a full stack trace?

**Comment by blset** [comment] 2019-01-16 16:01
In fact, it does nt work even after ther is one product


I cannot post a product to the store through the api,
there is no error but the product is not saved

GIT
  remote: https://github.com/spree-contrib/spree_i18n.git
  revision: 56d8f7087a5d661dc0e02576e528730c10fa8ad0
  specs:
    spree_i18n (3.3.2)
      i18n_data
      kaminari-i18n
      rails-i18n
      routing-filter
      spree_core (>= 3.1.0, < 4.0)
      spree_extension

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.2)
      actionpack (= 5.2.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.2)
      actionpack (= 5.2.2)
      actionview (= 5.2.2)
      activejob (= 5.2.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.2)
      actionview (= 5.2.2)
      activesupport (= 5.2.2)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.2)
      activesupport (= 5.2.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.2)
      activesupport (= 5.2.2)
      globalid (>= 0.3.6)
    activemerchant (1.90.0)
      activesupport (>= 4.2)
      builder (>= 2.1.2, < 4.0.0)
      i18n (>= 0.6.9)
      nokogiri (~> 1.4)
    activemodel (5.2.2)
      activesupport (= 5.2.2)
    activerecord (5.2.2)
      activemodel (= 5.2.2)
      activesupport (= 5.2.2)
      arel (>= 9.0)
    activestorage (5.2.2)
      actionpack (= 5.2.2)
      activerecord (= 5.2.2)
      marcel (~> 0.3.1)
    activesupport (5.2.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    acts-as-taggable-on (6.0.0)
      activerecord (~> 5.0)
    acts_as_list (0.9.17)
      activerecord (>= 3.0)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    ansi (1.5.0)
    archive-zip (0.11.0)
      io-like (~> 0.3.0)
    arel (9.0.0)
    ast (2.4.0)
    autoprefixer-rails (9.4.5)
      execjs
    awesome_nested_set (3.1.4)
      activerecord (>= 4.0.0, < 5.3)
    bcrypt (3.1.12)
    better_errors (2.5.0)
      coderay (>= 1.0.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
    bindex (0.5.0)
    binding_of_caller (0.8.0)
      debug_inspector (>= 0.0.1)
    bootsnap (1.3.2)
      msgpack (~> 1.0)
    bootstrap-sass (3.4.0)
      autoprefixer-rails (>= 5.2.1)
      sassc (>= 2.0.0)
    builder (3.2.3)
    byebug (10.0.2)
    camertron-eprun (1.1.1)
    cancancan (2.3.0)
    canonical-rails (0.2.4)
      rails (>= 4.1, < 5.3)
    capybara (3.12.0)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.2)
      xpath (~> 3.2)
    carmen (1.0.2)
      activesupport (>= 3.0.0)
    childprocess (0.9.0)
      ffi (~> 1.0, >= 1.0.11)
    chromedriver-helper (2.1.0)
      archive-zip (~> 0.10)
      nokogiri (~> 1.8)
    cldr-plurals-runtime-rb (1.0.1)
    climate_control (0.2.0)
    coderay (1.1.2)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.4)
    crass (1.0.4)
    css_parser (1.6.0)
      addressable
    daemons (1.3.1)
    debug_inspector (0.0.3)
    deface (1.3.2)
      nokogiri (>= 1.6)
      polyglot
      rails (>= 4.1)
      rainbow (>= 2.1.0)
    devise (4.4.3)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    devise-encryptable (0.2.0)
      devise (>= 2.1.0)
    doorkeeper (5.0.2)
      railties (>= 4.2)
    erubi (1.8.0)
    eventmachine (1.2.7)
    execjs (2.7.0)
    fast_jsonapi (1.5)
      activesupport (>= 4.2)
    ffaker (2.10.0)
    ffi (1.9.25)
    friendly_id (5.2.5)
      activerecord (>= 4.0.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    haml (5.0.4)
      temple (>= 0.8.0)
      tilt
    highline (2.0.0)
    htmlentities (4.3.4)
    i18n (1.5.2)
      concurrent-ruby (~> 1.0)
    i18n_data (0.9.1)
    interception (0.5)
    io-like (0.3.0)
    jaro_winkler (1.5.1)
    jbuilder (2.8.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.3)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    json (2.1.0)
    kaminari (1.0.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.0.1)
      kaminari-activerecord (= 1.0.1)
      kaminari-core (= 1.0.1)
    kaminari-actionview (1.0.1)
      actionview
      kaminari-core (= 1.0.1)
    kaminari-activerecord (1.0.1)
      activerecord
      kaminari-core (= 1.0.1)
    kaminari-core (1.0.1)
    kaminari-i18n (0.5.0)
      kaminari
      rails
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    mailcatcher (0.2.4)
      eventmachine
      haml
      i18n
      json
      mail
      sinatra
      skinny (>= 0.1.2)
      sqlite3-ruby
      thin
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (0.9.2)
    mime-types (3.2.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2018.0812)
    mimemagic (0.3.3)
    mini_magick (4.8.0)
    mini_mime (1.0.1)
    mini_portile2 (2.4.0)
    minitest (5.11.3)
    minitest-reporters (1.3.5)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    monetize (1.9.0)
      money (~> 6.12)
    money (6.13.2)
      i18n (>= 0.6.4, <= 2)
    msgpack (1.2.6)
    multi_json (1.13.1)
    mustermann (1.0.3)
    nio4r (2.3.1)
    nokogiri (1.10.1)
      mini_portile2 (~> 2.4.0)
    orm_adapter (0.5.0)
    paperclip (6.1.0)
      activemodel (>= 4.2.0)
      activesupport (>= 4.2.0)
      mime-types
      mimemagic (~> 0.3.0)
      terrapin (~> 0.6.0)
    parallel (1.12.1)
    paranoia (2.4.1)
      activerecord (>= 4.0, < 5.3)
    parser (2.5.3.0)
      ast (~> 2.4.0)
    pg (1.1.4)
    polyglot (0.3.5)
    powerpack (0.1.2)
    premailer (1.11.1)
      addressable
      css_parser (>= 1.6.0)
      htmlentities (>= 4.0.0)
    premailer-rails (1.10.2)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    pry (0.12.2)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
    pry-byebug (3.6.0)
      byebug (~> 10.0)
      pry (~> 0.10)
    pry-rails (0.3.9)
      pry (>= 0.10.4)
    pry-rescue (1.5.0)
      interception (>= 0.5)
      pry (>= 0.12.0)
    pry-stack_explorer (0.4.9.3)
      binding_of_caller (>= 0.7)
      pry (>= 0.9.11)
    public_suffix (3.0.3)
    puma (3.12.0)
    rabl (0.13.1)
      activesupport (>= 2.3.14)
    rack (2.0.6)
    rack-protection (2.0.5)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.2)
      actioncable (= 5.2.2)
      actionmailer (= 5.2.2)
      actionpack (= 5.2.2)
      actionview (= 5.2.2)
      activejob (= 5.2.2)
      activemodel (= 5.2.2)
      activerecord (= 5.2.2)
      activestorage (= 5.2.2)
      activesupport (= 5.2.2)
      bundler (>= 1.3.0)
      railties (= 5.2.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    rails-i18n (5.1.2)
      i18n (>= 0.7, < 2)
      railties (>= 5.0, < 6)
    railties (5.2.2)
      actionpack (= 5.2.2)
      activesupport (= 5.2.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rainbow (3.0.0)
    rake (12.3.2)
    ransack (2.1.1)
      actionpack (>= 5.0)
      activerecord (>= 5.0)
      activesupport (>= 5.0)
      i18n
    rb-fsevent (0.10.3)
    rb-inotify (0.10.0)
      ffi (~> 1.0)
    regexp_parser (1.3.0)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    routing-filter (0.6.2)
      actionpack (>= 4.2, < 6)
      activesupport (>= 4.2, < 6)
    rubocop (0.61.1)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.5, != 2.5.1.1)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.4.0)
    ruby-progressbar (1.10.0)
    ruby_dep (1.5.0)
    ruby_parser (3.12.0)
      sexp_processor (~> 4.9)
    rubyzip (1.2.2)
    sass (3.7.3)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sassc (2.0.0)
      ffi (~> 1.9.6)
      rake
    select2-rails (3.5.9.1)
      thor (~> 0.14)
    selenium-webdriver (3.141.0)
      childprocess (~> 0.5)
      rubyzip (~> 1.2, >= 1.2.2)
    sexp_processor (4.11.0)
    sinatra (2.0.5)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.5)
      tilt (~> 2.0)
    skinny (0.2.2)
      eventmachine (~> 1.0)
      thin
    spree (3.7.0.rc1)
      spree_api (= 3.7.0.rc1)
      spree_backend (= 3.7.0.rc1)
      spree_cmd (= 3.7.0.rc1)
      spree_core (= 3.7.0.rc1)
      spree_frontend (= 3.7.0.rc1)
      spree_sample (= 3.7.0.rc1)
    spree_api (3.7.0.rc1)
      doorkeeper (~> 5.0)
      fast_jsonapi (~> 1.5)
      rabl (~> 0.13.1)
      spree_core (= 3.7.0.rc1)
      versioncake (~> 3.4.0)
    spree_auth_devise (3.4.2)
      devise (~> 4.4.0)
      devise-encryptable (= 0.2.0)
      spree_core (>= 3.1.0, < 4.0)
      spree_extension
    spree_backend (3.7.0.rc1)
      bootstrap-sass (~> 3.4)
      jquery-rails (~> 4.3)
      jquery-ui-rails (~> 6.0.1)
      select2-rails (= 3.5.9.1)
      spree_api (= 3.7.0.rc1)
      spree_core (= 3.7.0.rc1)
    spree_cmd (3.7.0.rc1)
      thor (~> 0.14)
    spree_core (3.7.0.rc1)
      activemerchant (~> 1.67)
      acts-as-taggable-on (~> 6.0)
      acts_as_list (~> 0.8)
      awesome_nested_set (~> 3.1.3)
      cancancan (~> 2.0)
      carmen (~> 1.0.0)
      deface (~> 1.0)
      ffaker (~> 2.2)
      friendly_id (~> 5.2.1)
      highline (~> 2.0.0)
      kaminari (~> 1.0.1)
      mini_magick (~> 4.8.0)
      monetize (~> 1.9)
      money (~> 6.13)
      paperclip (~> 6.1.0)
      paranoia (~> 2.4.1)
      premailer-rails
      rails (~> 5.2.1, >= 5.2.1.1)
      ransack (~> 2.1.1)
      responders
      sprockets-rails
      state_machines-activerecord (~> 0.5)
      stringex
      twitter_cldr (~> 4.3)
    spree_extension (0.0.5)
      activerecord (>= 4.2)
    spree_frontend (3.7.0.rc1)
      bootstrap-sass (~> 3.4)
      canonical-rails (~> 0.2.3)
      jquery-rails (~> 4.3)
      spree_api (= 3.7.0.rc1)
      spree_core (= 3.7.0.rc1)
    spree_gateway (3.4.0)
      spree_core (>= 3.1.0, < 4.0)
      spree_extension
    spree_sample (3.7.0.rc1)
      spree_core (= 3.7.0.rc1)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13)
    sqlite3-ruby (1.3.3)
      sqlite3 (>= 1.3.3)
    state_machines (0.5.0)
    state_machines-activemodel (0.5.1)
      activemodel (>= 4.1, < 6.0)
      state_machines (>= 0.5.0)
    state_machines-activerecord (0.5.2)
      activerecord (>= 4.1, < 6.0)
      state_machines-activemodel (>= 0.5.0)
    stringex (2.8.5)
    temple (0.8.0)
    terrapin (0.6.0)
      climate_control (>= 0.0.3, < 1.0)
    thin (1.7.2)
      daemons (~> 1.0, >= 1.0.9)
      eventmachine (~> 1.0, >= 1.0.4)
      rack (>= 1, < 3)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.9)
    turbolinks (5.2.0)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    twitter_cldr (4.4.3)
      camertron-eprun
      cldr-plurals-runtime-rb (~> 1.0)
      tzinfo
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.20)
      execjs (>= 0.3.0, < 3)
    unicode-display_width (1.4.1)
    versioncake (3.4.0)
      actionpack (>= 3.2)
      activesupport (>= 3.2)
      railties (>= 3.2)
      tzinfo
    warden (1.2.8)
      rack (>= 2.0.6)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.7.0)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  better_errors
  binding_of_caller
  bootsnap (>= 1.1.0)
  byebug
  capybara (>= 2.15)
  chromedriver-helper
  coffee-rails (~> 4.2)
  ffaker
  jbuilder (~> 2.5)
  listen (>= 3.0.5, < 3.2)
  mailcatcher
  minitest-reporters
  pg (>= 0.18, < 2.0)
  pry
  pry-byebug
  pry-rails
  pry-rescue
  pry-stack_explorer
  puma (~> 3.11)
  rails (~> 5.2.2)
  rubocop
  ruby_parser
  sass-rails (~> 5.0)
  selenium-webdriver
  spree (~> 3.7.0.rc1)
  spree_auth_devise (~> 3.4)
  spree_gateway (~> 3.4)
  spree_i18n!
  spring
  spring-watcher-listen (~> 2.0.0)
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

RUBY VERSION
   ruby 2.5.3p105

BUNDLED WITH
   1.17.2

**Comment by damianlegawiec** [comment] 2019-01-16 16:12
@blset by full trace I've meant the HTTP request and the response from server - full server logs.

**Comment by blset** [comment] 2019-01-16 16:37
Finally, it wotks with curl like this

the problem is maybe with httparty which i was using previously



 curl -X POST --data 'product[name]=CACHE ROTULE DROIT&product[shipping_category_id]=1&product[price]=4.17' --header "X-Spree-Token: xxx"  http://127.0.0.1:3000/api/v1/products

{"id":2,"name":"CACHE ROTULE DROIT","description":null,"price":"417.0","display_price":"€417,00","available_on":"2019-01-16T16:33:21.438Z","slug":"cache-rotule-droit","meta_description":null,"meta_keywords":null,"shipping_category_id":1,"taxon_ids":[],"total_on_hand":0,"master":{"id":2,"name":"CACHE ROTULE DROIT","sku":"","price":"417.0","weight":"0.0","height":null,"width":null,"depth":null,"is_master":true,"slug":"cache-rotule-droit","description":null,"track_inventory":true,"cost_price":null,"option_values":[],"images":[],"display_price":"€417,00","options_text":"","in_stock":false,"is_backorderable":true,"is_orderable":true,"total_on_hand":0,"is_destroyed":false},"variants":[],"option_types":[],"product_properties":[],"classifications":[],"has_variants":false}%

**Comment by blset** [comment] 2019-01-16 16:52
the problem was I was forgetting the v1 in the url, in my first try, 

but it works without it for get queries, 

and silently fails for post then
