### ISSUE TITLE
Routes problem after update from 2-4-stable to 3-0-stable

### ISSUE THREAD

**Issue by mobentec** [spree/spree#6242] opened 2015-03-30 16:52 UTC
We're getting the following error when upgrading from 2-4-stable to 3-0-stable. :-(

```
Bundle complete! 30 Gemfile dependencies, 160 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
root@spree:~/mystore# bundle exec rake db:migrate
rake aborted!
ArgumentError: Invalid route name, already in use: 'api_current_order'
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here:
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:538:in `add_route'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1561:in `add_route'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1536:in `decomposed_match'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1517:in `block in match'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1507:in `each'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1507:in `match'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:689:in `map_method'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:650:in `get'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/spree-cfa72b4b0fed/api/config/routes.rb:68:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:881:in `block in namespace'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:881:in `namespace'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:1455:in `namespace'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/spree-cfa72b4b0fed/api/config/routes.rb:11:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:601:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:601:in `block in with_default_scope'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:600:in `with_default_scope'
/usr/local/rvm/gems/ruby-2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:421:in `eval_block'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/spree-cfa72b4b0fed/core/lib/spree/core/routes.rb:42:in `eval_block'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/spree-cfa72b4b0fed/core/lib/spree/core/routes.rb:34:in `block in draw_routes'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/spree-cfa72b4b0fed/core/lib/spree/core/routes.rb:34:in `each'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/spree-cfa72b4b0fed/core/lib/spree/core/routes.rb:34:in `draw_routes'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/spree-cfa72b4b0fed/core/config/routes.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `each'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `call'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `execute'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:27:in `updater'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/root/mystore/config/environment.rb:5:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/usr/local/rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
root@spree:~/mystore#
```

**Comment by JDutil** [comment] 2015-03-30 20:40
This is a duplicate of https://github.com/spree/spree/issues/6202 can you try removing `spring` form your Gemfile to see if that helps at all?

**Comment by jasonfb** [comment] 2015-04-06 17:04
I've worked around this before by finding the specific routes and just giving them 2 different names

**Closed** 2016-04-11 20:08 UTC
Labels: unverified
