### ISSUE TITLE
Error when canceling returned RMA

### ISSUE THREAD

**Issue by adaddeo** [spree/spree#5804] opened 2014-12-18 21:08 UTC
To reproduce on 2-4:
1. Successfully complete a return
2. Open up the Return Authorization
3. Hit the cancel button

Error:
Cannot transition reception_status via :cancel from :received (Reason(s): Reception status cannot transition via "cancel")

Should that cancel button not be shown at this point? Or should a transition be possible?

**Comment by pawelnguyen** [comment] 2015-01-15 15:23
I reproduced this bug on `master`
there are 2 "cancel" buttons on this page:
![selection_052](https://cloud.githubusercontent.com/assets/1530318/5758723/0c3b270a-9cc8-11e4-8ac4-f298ead66b3a.png)


I checked what exactly happens, and it's reproduction steps are the following:
1. Create and order, ship it 
2. Create a return authorization for it
3. ***Create a new customer return***
4. Go back to return authorization and try to cancel it

In case described by above it'll work fine.

The issue lies in [line item](https://github.com/spree/spree/blob/master/core/app/models/spree/return_item.rb#L62-L64) which are being [cancelled](https://github.com/spree/spree/blob/master/core/app/models/spree/return_authorization.rb#L71-L73) together with [return authorization](https://github.com/spree/spree/blob/master/core/app/models/spree/return_authorization.rb#L29)

Should it be possible to cancel a return authorization if it has any customer returns that have different state than `awaiting`? If not, an error message would be a good idea, or as suggested - hiding "cancel" button

**Comment by JDutil** [comment] 2015-01-15 17:13
I think once a customer return has been received you shouldn't be able to cancel return authorization anymore.

**Comment by pawelnguyen** [comment] 2015-01-15 20:14
Yes, I agree. Shall I create a PR with fix that would hide the button?

--
Paweł Nguyen

I think once a customer return has been received you shouldn't be able to
cancel return authorization anymore.

—
Reply to this email directly or view it on GitHub
<https://github.com/spree/spree/issues/5804#issuecomment-70121644>.

**Comment by JDutil** [comment] 2015-01-15 20:22
That would be awesome.

**Comment by athal7** [comment] 2015-01-15 21:47
customer return doesn't hold the state, return_item does. IMHO if one of the return items in the return authorization is still awaiting but another is received, you ought to be able to cancel the return authorization and the awaiting return item.

**Comment by pawelnguyen** [comment] 2015-01-16 14:32
@athal7 yes, `return_item` holds state that throws this error.

@athal7, so basicly in your mentioned situation there is a customer that:
1. Asked for a return authorization for two items
2. Returned only one

It's not a problem because when you create a return authorization with 2 items and then create a return with only 1, you can do a reimbursement for only this item. 
Why would you want to be able to cancel an item return by cancelling return authorization? There is no functionality to cancel an item return

**Comment by athal7** [comment] 2015-01-16 18:32
@pawelnguyen yes I know that you can reimburse only one item. there may be a case where someone wants to cancel a return authorization for the remaining unreturned item, which is behavior that i think ought to be supported. the earlier suggestion would disable that behavior.

**Comment by JDutil** [comment] 2015-03-09 15:18
Should have been fixed by https://github.com/spree/spree/pull/5898

**Closed by JDutil** 2015-03-09 15:18 UTC
Labels: unverified
