### ISSUE TITLE
Discount + Free Shipping Promotion not applying free shipping on 2-2-stable

### ISSUE THREAD

**Issue by carljhoover** [spree/spree#4746] opened 2014-05-27 18:40 UTC
Attempting to apply a promotion (with a coupon code) including a Whole Order Flat Percent adjustment and Free Shipping results in the flat percent adjustment being applied, but not the free shipping. On 2-2-stable.

The Flat Percent adjustment is applied in the cart, but the free shipping adjustments are not added to shipments created during the checkout flow? I attempted to isolate the issue and noticed that the 'apply_free_shipping_promotions' hook when leaving the delivery state uses Spree::PromotionHandler::FreeShipping to apply adjustments, but in its 'promotions' method it explicitly excludes promotions with a code. I introduced a decorator to activate the promotion from the order if there is one, but that resulted in the order having multiple promotion_ids through its association.

Not sure where to go from there...

**Comment by JDutil** [comment] 2015-02-03 19:28
This is a duplicate of #5420 where free shipping can't be applied until the shipments are created. I believe #5974 resolves this issue though as the free shipping would get applied once the shipments are created since the codes successfully applied to the order in the cart due to your working action.

**Closed by JDutil** 2015-02-03 19:28 UTC
Labels: unverified
