### ISSUE TITLE
Free shipping + whole order adjustment promotion doesnt work together

### ISSUE THREAD

**Issue by nimashariatian** [spree/spree#5421] opened 2014-09-26 16:17 UTC
this is most likely related to my other issue : #5420 
when creating a promotion that has free shipping + whole order adjustment, it only applies the whole order adjustment and ignores the shipping.

again not sure if this is intentded beheaviour or a bug

steps to reproduce:
1. create a compound promotion
![create_compound_promotion](https://cloud.githubusercontent.com/assets/210358/4423830/7bb0f29a-4598-11e4-8b5f-4a0909a9beb2.png)

2. apply the promotion
![apply_compound_promotion](https://cloud.githubusercontent.com/assets/210358/4423837/8a33ecf0-4598-11e4-8834-619a30a681e1.png)

3. proceed to checkout and verify the result 
![result_compound_promotion](https://cloud.githubusercontent.com/assets/210358/4423842/9387cf60-4598-11e4-9a74-79ce4eb58d54.png)

**Comment by JDutil** [comment] 2015-01-29 17:20
So I believe this is actually a duplicate of https://github.com/spree/spree/issues/5420 where free shipping can't be applied until the shipments are created.  I believe https://github.com/spree/spree/pull/5974 resolves this issue though as the free shipping would get applied once the shipments are created since the codes successfully applied to the order in the cart due to your working action..

**Closed by JDutil** 2015-01-29 17:20 UTC
Labels: unverified
