### ISSUE TITLE
Spree 3-0-stable: undefined method `kind?' for #<Spree::Zone:0x007ffe71e3c868>

### ISSUE THREAD

**Issue by dsadaka** [spree/spree#6218] opened 2015-03-23 21:43 UTC
Whenever the following line executes:

spree/core/app/models/spree/zone.rb:64:in `kind'

The surrounding code:
```ruby
    def kind
      if kind?
        super
      else
        not_nil_scope = members.where.not(zoneable_type: nil)
        zone_type = not_nil_scope.order('created_at ASC').pluck(:zoneable_type).last
        zone_type.demodulize.underscore if zone_type
      end
    end
```

For now, we've created a decorator implementing the 2.4 version of the kind method.

Any ideas why this is occurring?  I was kinda surprised noone has reported this since we can't enter an order on the backend or checkout on the front end without getting it.

**Comment by JDutil** [comment] 2015-03-24 12:19
Which version of ruby **and** rails are you using?  Also providing the other information from our [filing an issue guidelines](https://github.com/spree/spree/blob/master/CONTRIBUTING.md#filing-an-issue) would help as well.

**Comment by jozw** [comment] 2015-05-01 16:03
I am receiving the same error using rails 4.2.0 and ruby 2.1.5.

**Comment by dsadaka** [comment] 2015-05-01 19:49
This was caused by a missing migration.  Look for one that added the kind
attribute.






*Dan Sadaka, PresidentPristineEmail.com a service ofWebsite One, Inc.(305)
999-0151, (877) 706-7481*

*“The price of success is hard work, dedication to the job at hand, and
the determination that whether we win or lose, we have applied the best
of ourselves to the task at hand.” - Vince Lombardi*

**Comment by nishant-cyro** [comment] 2016-02-07 15:04
@dsadaka - can you close the issue if it is working fine now and caused by a missing migration?

cc: @priyank-gupta @damianlegawiec @Mafi88

**Closed** 2016-02-07 17:44 UTC
Labels: unverified
