### ISSUE TITLE
"We are unable to calculate shipping rates for the selected items." Spree 3.6.4

### ISSUE THREAD

**Issue by mices** [spree/spree#9167] opened 2019-01-08 05:41 UTC
Spree::Config.currency
"USD" 
 Spree::Config.default_country_id 
840 
When I try to add a state based zone the list of states are in the country Andora I want them to be states in the United States

**Comment by damianlegawiec** [comment] 2019-01-08 06:40
duplicate of https://github.com/spree/spree/issues/7823

**Closed by damianlegawiec** 2019-01-08 06:40 UTC
