### ISSUE TITLE
Multi Currency & Admin Panel: Customer Returns - Pre-tax total is displayed in incorrect currency 

### ISSUE THREAD

**Issue by grzeszet** [spree/spree#10925] opened 2021-03-25 13:38 UTC
## Context
It has been found that customer return, in order, is displayed with USD currency, not in the currency which in order was placed and paid (GBP or Euro). The currency displayed is the one that is set in store configuration.
Order on the screenshot was placed in GBP currency.

![image (4)](https://user-images.githubusercontent.com/74255636/112481527-64669080-8d77-11eb-9271-217cee7acfa2.png)

## Expected Behavior
Pre-Tax Total is displayed in the currency the order was placed in

## Actual Behavior
Pre-Tax Total is displayed in USD.

## Steps to Reproduce
1. Place an order in other than USD (use GBP or Euro)
2. Go to AP and process the order to shipment
3. Create a Return Authorization
4. Create a Customer Return
5. Observe Pre-Tax Total on this Customer Return

## Your Environment
Affected version: spee.4.3.0.alpha (ruby 2.7.2; rails 6.0.0)
Configuration:
gem ‘spree’
gem ‘spree_gateway’
gem ‘spree_auth_devise’
gem ‘spree_static_content’
gem ‘spree_related_products’
gem ‘spree_sitemap’
gem ‘spree_analytics_trackers’
gem ‘spree_braintree_vzero’
gem ‘spree_i18n’

**Comment by deepakhb2** [comment] 2021-03-27 22:50
I will work on this issue.

**Comment by rahul-bluebash** [comment] 2021-04-12 07:50
@deepakhb2 I think you need to double check the shipping methods in you app. There must be a shipping method available that contain zone which include UK country. This way, spree able to identify which shipping method need to use for calculating shipping rates.

I hope this helps. :)

**Comment by grzeszet** [comment] 2021-04-12 08:02
There is w workaround that should help with your problem. Simply do no not check "same as billing" on the address step, and input the shipping address manually. Hope it helps

**Comment by deepakhb2** [comment] 2021-04-12 17:34
Thank you @rahul-bluebash & @grzeszet.

The solution suggested by @rahul-bluebash worked for me. Shipping method for UK was missing. Thanks again.

**Comment by deepakhb2** [comment] 2021-04-12 18:00
Hi @grzeszet, It is working fine for me and the pre-tax total is added with same currency in which the order was placed. I followed the same steps and I tested this on master branch. Let me know if I am missing anything and we can take this separately to re-produce this issue. Thank you.
Attached screenshot for reference.
![Screenshot 2021-04-12 at 18 57 15](https://user-images.githubusercontent.com/1709978/114439455-e7357b00-9bc0-11eb-8b57-cf8646a84fca.png)

**Comment by rahul-bluebash** [comment] 2021-04-15 06:25
Hi @deepakhb2 I think you are checking in wrong tab, the issue is in the customer returns tab.
I tried a bit and able to replicate the issue.

This is because spree uses **Spree::Config[:currency]** as the currency for showing pre tax total of customer return.
https://github.com/spree/spree/blob/master/core/app/models/spree/customer_return.rb#L20

Its default set to USD, that's why the amount shown in dollar. If we change it from general settings, then issue will be fixed. 

@damianlegawiec FYI

**Comment by deepakhb2** [comment] 2021-04-15 21:33
Thank you @rahul-bluebash I missed it. I am not able to raise a return request. I am checking it now. Thanks again.

**Closed** 2021-07-14 14:21 UTC
Labels: Admin Panel ⚙️, Good First Issue, International :globe_with_meridians:
