### ISSUE TITLE
spec class seems wrong

### ISSUE THREAD

**Issue by masterkain** [spree/spree#6565] opened 2015-07-03 12:32 UTC
hello,
https://github.com/spree/spree/blob/master/core/spec/models/spree/calculator/shipping/price_sack_spec.rb

I don't believe this is the correct test for this class, and it's a dupe of this https://github.com/spree/spree/blob/master/core/spec/models/spree/calculator/price_sack_spec.rb

**Comment by nishant-cyro** [comment] 2016-02-04 09:11
@Mafi88 - I think the issue is already fixed by #6968 and we are good to close this one, right?

**Comment by Mafi88** [comment] 2016-02-04 11:59
@nishant-cyro Yes, you're right.

**Closed by Mafi88** 2016-02-04 11:59 UTC
Labels: verified
